PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>

INSERT {
    GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#>
    {
        ?section1 a was:LandSection, td:Thing;
				td:hasBase <http://localhost:1080/api/sections/1/>;
				was:hasCoordinates ?coords1;
       	was:growsCrop ?wheat;
				was:hasSoilMoisture ?moisture1.

        ?section2 a was:LandSection, td:Thing;
				td:hasBase <http://localhost:1080/api/sections/2/>;
				was:hasCoordinates ?coords2;
				was:growsCrop ?wheat;
				was:hasSoilMoisture ?moisture2.

        ?section3 a was:LandSection, td:Thing;
				td:hasBase <http://localhost:1080/api/sections/3/>;
				was:hasCoordinates ?coords3;
				was:growsCrop ?corn;
				was:hasSoilMoisture ?moisture3.
				
        ?section4 a was:LandSection, td:Thing;
				td:hasBase <http://localhost:1080/api/sections/4/>;
				was:hasCoordinates ?coords4;
        was:growsCrop ?corn;
				was:hasSoilMoisture ?moisture4.

        ?farm was:has ?section1.
        ?farm was:has ?section2.
        ?farm was:has ?section3.
        ?farm was:has ?section4.
    }.
} WHERE {
	?farm a was:Farm.
	?wheat a was:Wheat.
	?corn a was:Corn.

	?coords1 a was:Coordinates.
	?coords1 td:hasBase <http://localhost:1080/api/coordinates/1/>.
	?coords2 a was:Coordinates.
	?coords2 td:hasBase <http://localhost:1080/api/coordinates/2/>.
	?coords3 a was:Coordinates.
	?coords3 td:hasBase <http://localhost:1080/api/coordinates/3/>.
	?coords4 a was:Coordinates.
	?coords4 td:hasBase <http://localhost:1080/api/coordinates/4/>.

	?moisture1 a was:SoilMoisture.
	?moisture1 td:hasBase <http://localhost:1080/api/soilMoisture/1/>.
	?moisture2 a was:SoilMoisture.
	?moisture2 td:hasBase <http://localhost:1080/api/soilMoisture/2/>.
	?moisture3 a was:SoilMoisture.
	?moisture3 td:hasBase <http://localhost:1080/api/soilMoisture/3/>.
	?moisture4 a was:SoilMoisture.
	?moisture4 td:hasBase <http://localhost:1080/api/soilMoisture/4/>.

  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#section-", strUUID())) AS ?section1)
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#section-", strUUID())) AS ?section2)
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#section-", strUUID())) AS ?section3)
  	BIND(IRI(CONCAT("https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#section-", strUUID())) AS ?section4)
}