PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>

SELECT ?tractor WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#farm-9d762ba9-2faa-423a-a0b8-bbd527ad13d7> as ?farm)
   ?farm a was:Farm.    
   ?farm was:has ?tractor.
   ?tractor a was:Tractor.
 }
}
