PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX hmas: <https://purl.org/hmas/>
PREFIX td: <https://www.w3.org/2019/wot/td#>

SELECT ?td WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#farm-9d762ba9-2faa-423a-a0b8-bbd527ad13d7> as ?farm)
   ?farm a was:Farm.
   ?farm was:has ?tractor.
   ?tractor a was:Tractor. 
   ?tractor td:hasActionAffordance ?aff.
   ?tractor hmas:hasProfile ?td.
   ?aff a was:IrrigateAffordance. 
 }
}
