PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>

SELECT ?cropLabel WHERE {
GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#> {
   bind (<https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-jano#section-b054bd36-c8f2-4d4e-b1b8-16d3d34df928> as ?section)
   ?section a was:LandSection.
   ?section was:growsCrop ?crop.
 }
}